/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"

#define OPERAND_A 5
#define OPERAND_B 5

int *
suma_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	result = OPERAND_A + OPERAND_B;

	return &result;
}
