/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"

#define NUMBER_OF_OPERATIONS 10000

void
suma_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *suma_1_arg;
    struct timeval t, t2;
    int microsegundos;
	int counter = 0;

	#ifndef	DEBUG
		clnt = clnt_create (host, SUMA_PROG, SUMA_VERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

    gettimeofday(&t, NULL);

	while(counter < NUMBER_OF_OPERATIONS){
		result_1 = suma_1((void*)&suma_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		counter ++;
	}


    gettimeofday(&t2, NULL);
    microsegundos = ((t2.tv_usec - t.tv_usec)  + ((t2.tv_sec - t.tv_sec) * 1000000.0f));
    printf("Tardo %i microsegundos", microsegundos);

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	suma_prog_1 (host);
	exit (0);
}
